version: '3.9'

services:
  web:
    image:
      business_bot:latest
    build: ./
    command: sh -c "uvicorn call:app --reload --host 0.0.0.0 --port 8080"
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - .:/code
    restart: "always"
  bot:
    image:
      business_bot:latest
    build: ./
    command: sh -c "python main.py"
    volumes:
      - .:/code
    restart: "always"
